// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMZdia1ahoJ5ByS0LuhBn8srjhEXiODOg',
    appId: '1:825912203024:web:b942d0c33a925eb8ed3795',
    messagingSenderId: '825912203024',
    projectId: 'quickticket-4e36b',
    authDomain: 'quickticket-4e36b.firebaseapp.com',
    storageBucket: 'quickticket-4e36b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1cwHPN4LoxdQ5kCblhddZYnMls591Hww',
    appId: '1:825912203024:android:271a58aacf685c6ced3795',
    messagingSenderId: '825912203024',
    projectId: 'quickticket-4e36b',
    storageBucket: 'quickticket-4e36b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq6cdoXSNKIBQkGc8QKT0kgG3FrVMZp_c',
    appId: '1:825912203024:ios:321e103d04509cd4ed3795',
    messagingSenderId: '825912203024',
    projectId: 'quickticket-4e36b',
    storageBucket: 'quickticket-4e36b.appspot.com',
    iosClientId: '825912203024-df1ukfndbqvcf6tptoqenvlb1vk0sh1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq6cdoXSNKIBQkGc8QKT0kgG3FrVMZp_c',
    appId: '1:825912203024:ios:321e103d04509cd4ed3795',
    messagingSenderId: '825912203024',
    projectId: 'quickticket-4e36b',
    storageBucket: 'quickticket-4e36b.appspot.com',
    iosClientId: '825912203024-df1ukfndbqvcf6tptoqenvlb1vk0sh1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickticket',
  );
}
